FROM demonacz/nws171:latest

# installation tools
RUN apt-get update \
    && apt-get -y install wget p7zip

# unpacking Demona module files
RUN wget http://demona.cz/download/inst-demona-5.05.x.7z \
    && 7zr x inst-demona-5.05.x.7z \
    && rm inst-demona-5.05.x.7z

# cleanup unnecessary tools
RUN apt-get purge -y wget p7zip \
    && apt-get autoclean -y

# Demona specific entrypoint needed
COPY entrypoint.sh .

ENV NWS_MODULE demona
ENV NWS_ROTATE_LOGS true
ENV NWS_LOGS_DIR logs
ENV NWS_ROTATE_MODULES true

ENV GAME_OPTIONS_DEATH_LOGGING 1
ENV GAME_OPTIONS_DIFFICULTY_LEVEL 3
ENV GAME_OPTIONS_HEARTBEAT_LOGGING 1
ENV GAME_OPTIONS_LOG_MODEL_ERRORS 1

ENV SERVER_OPTIONS_2DA_CACHE_SIZE 64
ENV SERVER_OPTIONS_ALLOW_LOCAL_CHARS 0
ENV SERVER_OPTIONS_DISABLE_AUTOSAVE 1
ENV SERVER_OPTIONS_DISALLOW_SHOUTING 1
ENV SERVER_OPTIONS_EXAMINE_CR_ON_CREATURES 0
ENV SERVER_OPTIONS_EXAMINE_EFFECTS_ON_CREATURES 0
ENV SERVER_OPTIONS_GAMESPY_ENABLED 0
ENV SERVER_OPTIONS_MAX_CHAR_LEVEL 30
ENV SERVER_OPTIONS_MAX_HIT_POINTS 1
ENV SERVER_OPTIONS_MAX_PLAYERS 64
ENV SERVER_OPTIONS_ONE_PARTY_ONLY 0
ENV SERVER_OPTIONS_PVP_SETTINGS 2
ENV SERVER_OPTIONS_RESTORE_SPELL_USES_ON_LOGIN 1
ENV SERVER_OPTIONS_SERVER_NAME "Demona PW (http://demona.cz/)"
ENV SERVER_OPTIONS_SHOW_DM_JOINED_MESSAGE 0
ENV SERVER_OPTIONS_SUPPRESS_BASE_SERVERVAULT 1

ENTRYPOINT [ "./entrypoint.sh" ]
